### ISSUE TITLE
Update podspec to support version 0.7

### ISSUE THREAD

**Issue by timgcarlson** [VojtaStavik/Trackable#5]
Currently it's set to the non-swift 3 version 0.6.

**Comment by VojtaStavik** [comment]
Thank you for the bug report @timgcarlson !

**Comment by timgcarlson** [comment]
I think you still have to submit the updated podspec to Trunk so that 0.7 is the version used in Cocoapods.

From the [Cocoapods guide](https://guides.cocoapods.org/making/specs-and-specs-repo.html):
> Submit your Podspec to Trunk with `pod trunk push NAME.podspec`

BTW, I'm really digging Trackable! It really makes Mixpanel more enjoyable to work with. I'll let you know if we end up using it in our app.
